# Generated by Django 4.0 on 2022-02-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_steamid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='laps_lead',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='podiums',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='races_started',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='safety_rating',
            field=models.IntegerField(default='100'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wins',
            field=models.IntegerField(default='0'),
        ),
    ]
