# Generated by Django 4.0 on 2022-02-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_track_alter_race_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='race',
            name='race_bool',
            field=models.BooleanField(default=True),
        ),
    ]
