# Generated by Django 4.0 on 2022-02-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0003_race_name_race_race_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='info',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='race',
            name='practice_time',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='race',
            name='quli_time',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='race',
            name='race_laps',
            field=models.IntegerField(default=5),
        ),
    ]
