# Generated by Django 4.0 on 2022-02-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0004_race_info_race_practice_time_race_quli_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='port_number',
            field=models.IntegerField(default=8080),
        ),
        migrations.AddField(
            model_name='race',
            name='server_ip',
            field=models.CharField(default='195.211.11.141', max_length=20),
        ),
    ]
