# Generated by Django 4.0.2 on 2022-02-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0008_car_car_image_race_info_track_track_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mod_link',
            field=models.FileField(blank=True, upload_to='mods'),
        ),
    ]
