# Generated by Django 4.0 on 2022-02-22 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0008_car_car_image_race_info_track_track_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='car',
        ),
        migrations.CreateModel(
            name='cars_for_the_race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.car')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.race')),
            ],
        ),
    ]
