# Generated by Django 4.0.2 on 2022-02-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0009_car_mod_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='mod_link',
        ),
        migrations.AddField(
            model_name='race',
            name='mod_link',
            field=models.FileField(blank=True, upload_to='mods'),
        ),
    ]
