# Generated by Django 4.0 on 2022-02-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0009_remove_race_car_cars_for_the_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='mod_link',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
