# Generated by Django 4.0.2 on 2022-02-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0010_remove_car_mod_link_race_mod_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='quaulify_time',
            new_name='qualify_time',
        ),
        migrations.AlterField(
            model_name='race',
            name='mod_link',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
