# Generated by Django 4.0.2 on 2022-02-21 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0011_rename_quaulify_time_race_qualify_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='qualify_time',
            new_name='quaulify_time',
        ),
    ]
